# -*- coding: utf-8 -*-
"""Capstone Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Mar23226/5eec21916555253871f0fef9f0dfc8cf/-capstone-project.ipynb
"""

!pip install pandas
!pip install matplotlib

import pandas as pd
import matplotlib as plt
import numpy as np

df=pd.read_csv('https://raw.githubusercontent.com/trendct/datasets/master/0415-ct-professors/ct-professor-salaries.csv')
df

"""Analysis of college teacher salaries. What are the differences btw state and ivy leauge?

"""

df.head(10)
df=df[['City','Average All Pay','Associate Professor']]
df

df.mean()

"""mean of average salary is 73487 for average college professor"""

df.median()

"""average median for associate college professor is 69187"""

import numpy as np
import matplotlib.pyplot as plt
df.hist()

df=df[['City','Average All Pay','Lecturer']]
df

import numpy as np
import matplotlib.pyplot as plt
df.hist()

"""Mean of Lecturer salary?"""

df.mean()

"""Differences btw Yale and State Colleges?

"""

df=df[['College','City','Average All Pay']]
df

df.boxplot()